### ISSUE TITLE
Some doubts about result

### ISSUE THREAD

**Issue by xlk369293141** [salesforce/MultiHopKG#26]
Hello, thank for sharing your code. 
       But, I notice that the result of ConvE in your paper is much higher than the origin paper. Are the testing procedures the same for both?  I guess, may have added beam search for ConvE, or something different?
       Hope for your reply soon.

**Comment by todpole3** [comment]
Good catch. I recall it is because we evaluated only evaluated on subject-rel-? prediction while the original ConvE paper evaluated on both ?-rel-object and subject-rel-?. 

Our multi-hop reasoning results, however, is comparable to all previous work in the sense the all are reported in subject-rel-? only.

**Comment by xlk369293141** [comment]
Oh, That is. But it is still confused that using invese triples in training but not testing.
I have another question about FB15k-237 and WN18RR. Enitties of thes two datasets are just mid(/m/07pd_j) or  number string(02174461). How can I find the real entity name of them like NELL-995.

**Comment by todpole3** [comment]
You need to download a freebase data dump and write a script to map the IDs to names I believe. Our models do not use the names.
